# Generated by Django 4.0.2 on 2023-05-02 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('passenger_ids', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('transaction_id', models.CharField(max_length=30, unique=True)),
                ('number_tickets', models.IntegerField()),
                ('seat_codes', models.CharField(max_length=1000)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('cancelled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FlightInfo',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('flight_number', models.CharField(max_length=30)),
                ('flight_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seat_list', models.CharField(max_length=5000)),
                ('departure_airport', models.CharField(max_length=100)),
                ('destination_airport', models.CharField(max_length=100)),
                ('arrival_date', models.DateTimeField()),
                ('departure_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PassengerSeatInfo',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('seat_class', models.CharField(choices=[('business', 'Business Class'), ('economy', 'Economy Class')], max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('passenger_type', models.CharField(max_length=30)),
                ('reserved', models.BooleanField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.bookings')),
            ],
        ),
    ]
