# Generated by Django 4.0.2 on 2023-05-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airports',
            old_name='name',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='passengerseatinfo',
            name='passenger_type',
            field=models.CharField(choices=[('first', 'First Class'), ('business', 'Business Class')], max_length=30),
        ),
        migrations.AlterField(
            model_name='passengerseatinfo',
            name='seat_class',
            field=models.CharField(choices=[('first', 'First Class'), ('business', 'Business Class'), ('economy', 'Economy Class')], max_length=30),
        ),
    ]
